In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
import os
import numpy as np
import pandas as pd
from collections import Counter
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.corpus import stopwords
stop = stopwords.words('english')
import string
punctuations = list(string.punctuation)
stop = stop + punctuations

In [16]:

def ModPosTag(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# def simple_clean(words):
#     output_words = [w.lower() for w in words if not w.lower() in stop]
#     return output_words

def simple_clean(words):
    output_words = [w for w in words if not w in stop]
    return output_words


# def complex_clean(words):
#     output_words = []
#     for w in words:
#         if w.lower() not in stop:
#             pos = pos_tag([w])
#             clean_w = lemmatizer.lemmatize(w, pos = ModPosTag(pos[0][1]))
#             output_words.append(clean_w.lower())
#     return output_words

# remove lemetize
def complex_clean(words):
    output_words = []
    for w in words:
        if w not in stop:
            pos = pos_tag([w])
            clean_w = lemmatizer.lemmatize(w, pos = ModPosTag(pos[0][1]))
            output_words.append(clean_w)
    return output_words


def read_words(words_dir):

    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    #features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    all_words = []
    all_words_heading = []
    major_words_abstract = []
    for fil in files:
        with open(fil) as fi:
            words_abstract = []
            for i, line in enumerate(fi):
                if (i == 0):
                    temp = line.split()
                    temp1 = simple_clean(temp)
                    
                    words_abstract += temp1
                    all_words_heading += temp1
                else:
                    temp = line.split()
                    temp1 = complex_clean(temp)
                    print(fil)
                    print()
                    print(temp1)
                    words_abstract += temp1
                    all_words += temp1

            major_words_abstract.append(words_abstract)
            len(all_words)
    return major_words_abstract, all_words, all_words_heading

def tag_updater(df, variable_code):
    for key, values in variable_code.items():
        temp = str(key)
        area = variable_code[key]
        for val in area:
            df.at[val-1, temp] = 1

    return df


def read_tags(words_dir):
    files = [os.path.join(words_dir, fi) for fi in os.listdir(words_dir)]

    # features_matrix = np.zeros((len(files), 3000))
    docID = 0;
    tagss = set()
    for fil in files:
        docID+=1
        with open(fil) as fi:
            for i, line in enumerate(fi):
                temp = line.split(',')
                tagss.update(temp)
    return docID, tagss




In [17]:
mydict = {}

def read_files(words_directory, tags_directory):

    wo = [os.path.join(words_directory, wi) for wi in os.listdir(words_directory)]
    ta = [os.path.join(tags_directory, ti) for ti in os.listdir(tags_directory)]
    ctr=0
    for (ab, t) in zip(wo, ta):
        ctr +=1
        with open(t) as su:
            for i, line in enumerate(su):
                tag = line.split(',')
                for q in tag:
                    if q not in mydict:
                        mydict[q] = []
                    mydict[q].append(ctr)

    return mydict,ctr

def extract_features(Words, features):
    feature_matrix = np.zeros((len(Words), len(features)))
    docID = 0
    for doc in Words:
        for word in doc:
            for i in range(len(features)):
                if features[i] == word:
                    wordID = i
                    feature_matrix[docID, wordID] += 1
        docID = docID + 1
    np.shape(feature_matrix)
    print(feature_matrix)
    return feature_matrix

In [18]:
words_dir = 'abstract'
tags_directory = 'tags'
Words, all_words, all_words_heading = read_words(words_dir)


abstract\1.txt

['There', 'many', 'study', 'researcher', 'attempt', 'classify', 'student', 'attentiveness.', 'Many', 'approach', 'depend', 'qualitative', 'analysis', 'lack', 'quantitative', 'analysis.', 'Therefore,', 'work', 'focus', 'bridging', 'gap', 'qualitative', 'quantitative', 'approach', 'classify', 'student', 'attentiveness.', 'Thus,', 'research', 'applies', 'machine', 'learn', 'algorithm', '(K-means', 'SVM)', 'automatically', 'classify', 'student', 'attentive', 'inattentive', 'use', 'data', 'consumer', 'RGB-D', 'sensor.', 'Results', 'research', 'use', 'improve', 'teach', 'strategy', 'instructor', 'level', 'aid', 'instructor', 'implement', 'personalize', 'learn', 'systems,', 'National', 'Academy', 'Engineering', 'Grand', 'Challenge.', 'This', 'research', 'applies', 'machine', 'learn', 'algorithm', 'educational', 'setting.', 'Data', 'algorithm', 'use', 'instructor', 'provide', 'valuable', 'feedback', 'effectiveness', 'instructional', 'strategy', 'pedagogies.', 'Instructors', 'us

abstract\18.txt

['This', 'paper', 'proposes', 'new', 'fuzzy', 'multicategory', 'support', 'vector', 'machine', '(FMSVM)', 'classifier.', 'The', 'main', 'idea', 'propose', 'FMSVM', 'us', 'knowledge', 'ambiguity', 'associate', 'membership', 'sample', 'give', 'class', 'relative', 'location', 'sample', 'origin.', 'Compared', 'exist', 'SVMs,', 'new', 'propose', 'FMSVM', 'us', 'L2-norm', 'objective', 'function', 'improvement', 'aspect', 'classification', 'accuracy', 'reduce', 'effect', 'noise', 'outliers.']
abstract\19.txt

['This', 'paper', 'investigates', 'improve', 'fuzzy', 'multicategory', 'support', 'vector', 'machine', 'classifier', '(IFMSVM).', 'It', 'us', 'knowledge', 'ambiguity', 'associate', 'membership', 'data', 'sample', 'give', 'class', 'relative', 'location', 'origin,', 'improve', 'classification', 'performance', 'high', 'generalization', 'capability.', 'In', 'aspects,', 'classify', 'accuracy', 'new', 'algorithm', 'well', 'classical', 'support', 'vector', 'classification', 'al

abstract\30.txt

['The', 'Federal', 'Big', 'Data', 'Working', 'Group', 'support', 'Federal', 'Big', 'Data', 'Initiative', 'endorse', 'Federal', 'Government', 'agencies.', 'This', 'work', 'group', 'us', 'meetups', 'onsite', 'virtual', 'participation', 'share', 'best', 'practice', 'implementation', 'Big', 'Data', 'application', 'government', 'science', 'communities.', 'Decision-makers', 'scientific', 'community', 'interact', 'data', 'science', 'order', 'take', 'advantage', 'Big', 'Data', 'transformation', 'information', 'use', 'science,', 'decision', 'support,', 'data', 'discovery', 'data', 'publishing.', 'The', 'work', 'group', 'federates', 'use', 'cases,', 'data', 'publications,', 'solution', 'technologies.', 'The', 'range', 'topic', 'illustrate', 'keynote', 'panel', 'discussion', 'recent', 'Big', 'Data', 'conference', 'summary', 'recent', 'work', 'group', 'meetups.']
abstract\31.txt

['This', 'paper', 'outline', 'big', 'data', 'infrastructure', 'processing', 'data', 'streams.', 'Our',

abstract\40.txt

['Customer', 'Relationship', 'Management', '(CRM)', 'currently', 'fast', 'grow', 'sector', 'enterprise', 'software,', 'estimate', 'increase', 'worldwide', '2017.', 'CRM', 'technology', 'increasingly', 'use', 'data', 'mining', 'primitive', 'across', 'multiple', 'applications.', 'At', 'time,', 'growth', 'big', 'data', 'lead', 'evolution', 'open', 'source', 'big', 'data', 'software', 'stack', '(primarily', 'power', 'Apache', 'software)', 'rival', 'traditional', 'enterprise', 'database', '(RDBMS)', 'stacks.', 'New', 'technology', 'Kafka,', 'Storm,', 'HBase', 'significantly', 'enrich', 'open', 'source', 'stack,', 'alongside', 'establish', 'technology', 'Hadoop', 'MapReduce', 'Mahout.', 'Today,', 'enterprise', 'choice', 'make', 'regard', 'stack', 'choose', 'power', 'big', 'data', 'applications.', 'However,', 'publish', 'study', 'literature', 'enterprise', 'big', 'data', 'pipeline', 'built', 'use', 'open', 'source', 'component', 'support', 'CRM.', 'Specific', 'question', 'ent

abstract\49.txt

['As', 'large', 'amount', 'data', 'generate', 'healthcare', 'industry,', 'big', 'data', 'technology', 'use', 'process', 'data.', 'Tobacco', 'smoking', 'significant', 'among', 'youth', 'United', 'States.', 'In', 'research,', 'use', 'big', 'data', 'technique', 'R', 'Tableau', 'explore', 'tobacco', 'smoking', 'trend', 'among', 'youth', 'United', 'States.', 'Results', 'indicate', 'number', 'youth', 'male', 'smoker', 'youth', 'female', 'smokers.', 'The', 'result', 'also', 'indicate', '51', 'percent', 'current', 'youth', 'smoker', 'want', 'quit', 'smoking.']
abstract\5.txt

['Text', 'categorization', '(TC)', 'important', 'component', 'many', 'information', 'organization', 'information', 'management', 'tasks.', 'Two', 'key', 'issue', 'TC', 'feature', 'cod', 'classifier', 'design.', 'The', 'Euclidean', 'distance', 'usually', 'chosen', 'similarity', 'measure', 'K-nearest', 'neighbor', 'classification', 'algorithm.', 'All', 'feature', 'vector', 'different', 'function', 'describe

abstract\a12.txt

['There', '700,000', 'Rheumatoid', 'Arthritis', '(RA)', 'patient', 'Japan,', 'number', 'patient', 'increase', '30,000', 'annually.', 'The', 'early', 'detection', 'appropriate', 'treatment', 'accord', 'progression', 'RA', 'effective', 'improve', "patient's", 'prognosis.', 'The', 'modify', 'Total', 'Sharp', '(mTS)', 'score', 'widely', 'use', 'progression', 'evaluation', 'Rheumatoid', 'Arthritis.', 'The', 'mTS', 'score', 'assessment', 'hand', 'foot', 'X-ray', 'image', 'require', 'several', 'time', 'year,', 'take', 'long', 'time.', 'The', 'automatic', 'mTS', 'score', 'calculation', 'system', 'required.', 'This', 'paper', 'proposes', 'finger', 'joint', 'detection', 'method', 'mTS', 'score', 'estimation', 'method', 'use', 'support', 'vector', 'machine.', 'Experimental', 'result', '45', 'RA', "patient's", 'X-ray', 'image', 'show', 'propose', 'method', 'detects', 'finger', 'joint', 'accuracy', '81.4', '%,', 'estimate', 'erosion', 'JSN', 'score', 'accuracy', '50.9,', '64.3', '

abstract\a25.txt

['This', 'paper', 'proposes', 'new', 'branch', 'neural', 'networks,', 'call', '"neurite', 'networks",', 'neural', 'network', 'grows,', 'i.e.', 'embryological', 'component.', 'The', 'artificial', 'neurite', 'network', 'introduce', 'base', 'cellular', 'automaton', '(CA)', 'network', 'whose', 'branching', 'genetically', 'programmed', '(i.e.', 'grown', 'control', 'genetic', 'algorithm).', 'A', 'sequence', 'CA', 'signal', 'sent', 'middle', 'CA', '"trail".', 'When', 'signal', 'hit', 'end', 'trail,', 'make', 'trail', 'extend,', 'turn', 'left,', 'turn', 'right,', 'branch', 'left,', 'branch', 'right,', 'split,', 'etc.,', 'depend', 'upon', 'state', 'CA', 'signal.', 'These', 'signal', 'sequence', 'treat', 'chromosome', 'genetic', 'algorithm.', 'Once', 'CA', 'network', 'formed,', 'second', 'set', 'CA', 'state', 'transition', 'rule', 'switch', 'make', 'behave', 'like', 'neural', 'network.', 'The', 'fitness', 'CA', 'base', 'neural', 'network', 'measure', 'term', 'well', 'control', 

abstract\a33.txt

['The', 'use', 'flash', 'device', 'analog', 'storage', 'analog', 'computation', 'result', 'highly', 'efficient', 'switched-capacitor', 'implementation', 'neural', 'networks.', 'The', 'standard', 'flash', 'device', 'suffers', 'severe', 'limitation', 'application', 'due', 'relatively', 'large', 'parasitic', 'overlap', 'capacitances.', 'This', 'paper', 'introduces', 'computational', 'concept,', 'circuit', 'architecture', 'explore', 'well', 'novel', 'flash-based', 'programmable', 'nonlinear', 'capacitor', 'much', 'improve', 'charge', 'domain', 'characteristic', 'application.', 'These', 'device', 'demonstrate', 'novel', 'circuit', 'consist', 'two', 'device', 'capable', 'compute', '5-bit', 'absolute-value-of-difference', 'energy', 'consumption', 'less', '1', 'pJ.<>']
abstract\a34.txt

['Deep', 'Learning', 'artificial', 'intelligence', 'function', 'imitates', 'mechanism', 'human', 'mind', 'processing', 'record', 'develop', 'shape', 'use', 'selection', 'construction.', 'The',

abstract\a41.txt

['In', 'parallel', 'rapid', 'development', 'prospective', 'system', 'last', '20', 'years,', 'many', 'method', 'apply', 'field.', 'One', 'deep', 'learn', 'network', 'attract', 'interest', 'researcher', 'recent', 'years.', 'The', 'DBN', '(Deep', 'Belief', 'Network),', 'train', 'one', 'layer', 'time', 'greedily,', 'us', 'unsupervised', 'learn', 'layer', 'compose', 'RBMs', '(Restricted', 'Boltzman', 'Machine),', 'become', 'turn', 'point', 'area.', 'In', 'study,', 'deep', 'learn', 'method', 'apply', 'recommender', 'system', 'problem.', 'The', 'Python-based', 'deep', 'learn', 'library,', 'Keras,', 'use', 'exist', 'learn', 'algorithm', 'compared.']
abstract\a42.txt

['Deep', 'Learning', 'appeal', 'learn', 'large', 'amount', 'unlabeled/unsupervised', 'data,', 'make', 'attractive', 'extract', 'meaningful', 'representation', 'pattern', 'big', 'data.', 'Deep', 'learning,', 'simplest', 'definition,', 'express', 'application', 'machine', 'learn', 'method', 'big', 'data.', 'In', 's

abstract\a51.txt

['This', 'paper', 'discus', 'emergence', 'cooperative', 'coordinate', 'behavior', 'joint', 'concurrent', 'learn', 'agent', 'use', 'deep', 'Q-learning.', 'Multi-agent', 'system', '(MAS)', 'arise', 'variety', 'domains.', 'The', 'collective', 'effort', 'one', 'main', 'building', 'block', 'many', 'fundamental', 'system', 'exist', 'world,', 'thus,', 'sequential', 'decision', 'make', 'uncertainty', 'collaborative', 'work', 'one', 'important', 'challenge', 'issue', 'intelligent', 'cooperative', 'multiple', 'agents.', 'However,', 'decision', 'cooperation', 'highly', 'sophisticated', 'complicate', 'agent', 'may', 'certain', 'share', 'goal', 'individual', 'goal', 'achieve', 'behavior', 'inevitably', 'influence', 'other.', 'Therefore,', 'attempt', 'explore', 'whether', 'agent', 'use', 'deep', 'Q-networks', '(DQN)', 'learn', 'cooperative', 'behavior.', 'We', 'use', 'double', 'pong', 'game', 'example', 'investigate', 'learn', 'divide', 'work', 'iterate', 'game', 'executions.', 'In

abstract\a63.txt

['Summary', 'form', 'given,', 'follows.', 'A', 'Hopfield', 'model', 'neural', 'network', 'useful', 'form', 'parallel', 'computer.', 'Such', 'neural', 'network', 'may', 'capable', 'arrive', 'problem', 'solution', 'much', 'speed', 'conventional,', 'sequential', 'approaches.', 'This', 'concept', 'apply', 'problem', 'generate', 'control', 'bit', 'multistage', 'interconnection', 'network.', 'A', 'Hopfield', 'model', 'neural', 'network', 'design', 'capable', 'rout', 'set', 'messages.', 'This', 'neural', 'network', 'solution', 'especially', 'useful', 'interconnection', 'network', 'self-routing', 'interconnection', 'network', 'irregular', 'structure.', 'Furthermore,', 'neural', 'network', 'rout', 'scheme', 'fault-tolerant.', 'Results', 'obtain', 'generate', 'route', '4*4', 'Benes', 'interconnection', 'network.<>']
abstract\a64.txt

['A', 'disturbance-rejection', 'neural', 'network', 'control', 'scheme', 'present', 'control', 'unknown', 'nonlinear', 'plant.', 'In', 'scheme,', 

abstract\a72.txt

['A', 'USAF', 'sponsor', 'MITRE', 'research', 'team', 'undertook', 'four', 'separate,', 'domain-specific', 'case', 'study', 'Big', 'Data', 'applications.', 'Those', 'case', 'study', 'initial', 'investigation', 'question', 'whether', 'data', 'quality', 'issue', 'encounter', 'Big', 'Data', 'collection', 'substantially', 'different', 'cause,', 'manifestation,', 'detection', 'data', 'quality', 'issue', 'encounter', 'traditionally', 'size', 'data', 'collections.', 'The', 'study', 'address', 'several', 'factor', 'affect', 'Big', 'Data', 'Quality', 'multiple', 'levels,', 'include', 'collection,', 'processing,', 'storage.', 'Though', 'unexpected,', 'key', 'finding', 'study', 'reinforce', 'primary', 'factor', 'affect', 'Big', 'Data', 'reside', 'limitation', 'complexity', 'involve', 'handle', 'Big', 'Data', 'maintain', 'integrity.', 'These', 'concern', 'high', 'magnitude', 'provenance', 'data,', 'processing,', 'tool', 'use', 'prepare,', 'manipulate,', 'store', 'data.', 'Data', 

abstract\a80.txt

['The', 'Atmospheric', 'Radiation', 'Measurement', '(ARM)', 'Climate', 'Research', 'Facility', '(www.arm.gov)', 'provide', 'atmospheric', 'observation', 'diverse', 'climatic', 'regime', 'around', 'world.', 'Currently,', 'ARM', 'archive', '22', 'million', 'user', 'assessable', 'data', 'files,', 'primarily', 'store', 'NetCDF', 'file', 'format,', 'total', 'data', 'volume', 'close', 'one', 'Petabyte.', 'In', 'paper,', 'discus', 'ARM', 'currently', 'storing,', 'distributing,', 'catalog', 'visualize', 'large', 'volume', 'multi-dimensional', 'climate', 'observation', 'model', 'data', 'also', 'describe', 'future', 'plan.']
abstract\a81.txt

['The', 'advent', 'social', 'network', 'Internet-of-Things', 'result', 'unprecedented', 'capability', 'collecting,', 'share', 'analyze', 'massive', 'amount', 'data.', 'From', 'security', 'perspective,', 'Big', 'Data', 'may', 'seriously', 'weaken', 'confidentiality,', 'technique', 'improve', 'Big', 'Data', 'analytics', 'performance-includin

abstract\a88.txt

['Big', 'Data', 'contains', 'massive', 'information,', 'generate', 'heterogeneous,', 'autonomous', 'source', 'distribute', 'anonymous', 'platforms.', 'Since,', 'raise', 'extreme', 'challenge', 'organization', 'store', 'process', 'data.', 'Conventional', 'pathway', 'store', 'process', 'happen', 'collection', 'manual', 'step', 'consume', 'various', 'resources.', 'An', 'automate', 'real-time', 'online', 'analytical', 'process', 'cognitive', 'solution.', 'Therefore', 'need', 'state', 'art', 'approach', 'overcome', 'barrier', 'concern', 'currently', 'face', 'Big', 'Data', 'industry.', 'In', 'paper', 'propose', 'novel', 'architecture', 'automate', 'data', 'analytics', 'process', 'use', 'Nested', 'Automatic', 'Service', 'Composition', '(NASC)', 'CRoss', 'Industry', 'Standard', 'Platform', 'Data', 'Mining', '(CRISP-DM)', 'main', 'base', 'technology', 'solution.', 'NASC', 'well', 'define', 'scalable', 'technology', 'automate', 'multi-disciplined', 'problem', 'domains.', 'Since

In [19]:
cou, Tags = read_tags(tags_directory)
#df = pd.DataFrame(Tags)
Words = np.array(Words)
# exploring frequency of all words not in heading
import nltk
freq = nltk.FreqDist(all_words + all_words_heading)
common = freq.most_common(3000)
common = list(common)

features = []
features += [w[0] for w in common]
features += [w for w in all_words_heading if w not in common]
print(len(common))
print(len(features))


3000
4147


In [20]:


variable_code, ctr = read_files(words_dir, tags_directory)
columns = list(Tags)
rows = list(range(ctr))
dataFrame = np.zeros((len(rows), len(columns)))
#df = tag_updater(dataFrame, variable_code, columns)

df = pd.DataFrame(data = dataFrame, index = rows, columns = columns, dtype='int64')
# print(variable_code)
Y = tag_updater(df, variable_code)
#print(df.at[1, ' Machine learning '])
# for x in df['Computers']:
#     print(x)

display(Y)
Y.fillna(0, inplace=True)

X = extract_features(Words, features)
X_train = pd.DataFrame(data = X, index = rows, columns = features, dtype='int64')


# using binary relevance
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# initialize binary relevance multi-label classifier
# with a gaussian naive bayes base classifier
classifier = BinaryRelevance(GaussianNB())
# train
classifier.fit(X_train, Y)
# predict
#predictions = classifier.predict(X_train)
#print(predictions.toarray())
#print(accuracy_score(Y, predictions))

geographic location  Intelligent networks   Life estimation   \
0                      0                        0                  0   
1                      0                        0                  0   
2                      0                        0                  1   
3                      0                        0                  0   
4                      0                        0                  0   
5                      0                        0                  0   
6                      0                        0                  0   
7                      0                        0                  0   
8                      0                        0                  0   
9                      0                        0                  0   
10                     0                        0                  0   
11                     0                        0                  0   
12                     0                        0                  0   
13                     0                        0                  0   
14                     0                        0                  0   
15                     0                        0                  0   
16                     0                        0                  0   
17                     0                        0                  0   
18                     0                        0                  0   
19                     0                        0                  0   
20                     0                        0                  0   
21                     0                        0                  0   
22                     0                        0                  0   
23                     0                        0                  0   
24                     0                        0                  0   
25                     0                        0                  0   
26                     0                        0                  0   
27                     0                        0                  0   
28                     0                        0                  0   
29                     0                        0                  0   
..                   ...                      ...                ...   
106                    0                        0                  0   
107                    0                        0                  0   
108                    0                        0                  0   
109                    0                        0                  0   
110                    0                        0                  0   
111                    0                        0                  0   
112                    0                        0                  0   
113                    0                        0                  0   
114                    0                        0                  0   
115                    0                        0                  0   
116                    0                        0                  0   
117                    0                        0                  0   
118                    0                        0                  0   
119                    0                        0                  0   
120                    0                        0                  0   
121                    0                        0                  0   
122                    0                        0                  0   
123                    0                        0                  0   
124                    0                        0                  0   
125                    0                        0                  0   
126                    0                        0                  0   
127                    0                        0                  0   
128                    0                        0                  0   
129                    0                     

[[1. 5. 0. ... 0. 0. 0.]
 [4. 7. 3. ... 0. 0. 0.]
 [6. 3. 0. ... 0. 0. 0.]
 ...
 [7. 5. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]
 [0. 1. 4. ... 3. 3. 1.]]


BinaryRelevance(classifier=GaussianNB(priors=None),
        require_dense=[True, True])

In [23]:
words_dir = 'testing_2'
Words, waste1, waste2 = read_words(words_dir)
X = extract_features(Words, features)
rows = list(range(1))
X_test = pd.DataFrame(data = X, columns = features, dtype='int64')


[[0. 0. 0. ... 0. 0. 0.]]


In [24]:
display(X_test)
predictions = classifier.predict(X_test)

data  learn  The  use  neural  big  machine  Data  deep  network    ...     \
0     0      0    0    0       0    0        0     0     0        0    ...      

   Composition  A  method  choose  kernel  function  parameters  support  \
0            0     0       0       0       0         0           0        0   

   vector  machines  
0       0         0  

[1 rows x 4147 columns]

In [25]:
predictions
display(predictions)
predictions.shape[0]

<1x1774 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Column format>

1

In [ ]:
from scipy.sparse import csc_matrix
print(type(predictions))
a = predictions.nonzero()
#a.row[a.data]

In [ ]:
def find_index(self):
    A = self.tocoo()
    nz_mask = A.data != 0
    return (list(A.col[nz_mask]))

In [ ]:
print((predictions.shape[0], len(columns)))
dataFrame5 = np.zeros((predictions.shape[0], len(columns)))
ct = 0
for i in predictions:
    b = find_index(i)
    for j in b:
        dataFrame5[ct,j] +=1
    ct+=1
print(dataFrame5)
for i in dataFrame5:
    print(len(i))

In [ ]:
print(type(dataFrame))

converting = pd.DataFrame(data = dataFrame5, columns = columns, dtype='int64')
display(converting)

In [ ]:
df.to_csv('file_predicted_skills.csv', sep='\t', encoding='utf-8')

In [ ]:
we_have = []
print('------------------------TECHNICAL SKILLS REQUIRED-----------------------------')
for i in b:
    print(columns[i])
    we_have.append(columns[i])
    
#we_have.append('artificial intelligence')
#we_have.append('Machine learning algorithms')
#we_have.append('Support vector machines')
#we_have.append('Kernel')

print(we_have)

In [ ]:
#this is keyword extractor

In [ ]:
#next comes the wiki reader

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import nltk
import pickle


lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("english"))


def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return ''


def load_skill_set():

    skill_dict = dict()
    pick_file = open("final_skill_dict.pickle", "rb")
    skill_dict = pickle.load(pick_file)
    pick_file.close()
    return skill_dict


skill_dict = load_skill_set()


def get_skills(skill_dic,topic):

    # print("getting skill set for ",topic)
    skill_set = set()
    for word in topic.split(' '):
        # print("for word=",word)
        if word.strip().isalpha():
            word = word.strip().lower()
            wordnet_pos = get_wordnet_pos(nltk.pos_tag([word])[0][1])
            if wordnet_pos == '':
                word = lemmatizer.lemmatize(word)
            else:
                word = lemmatizer.lemmatize(word, wordnet_pos)

            try:
                curr_skill_set = skill_dic[word]
                # print("skill set=",curr_skill_set)
                if len(skill_set) == 0:
                    skill_set = curr_skill_set
                else:
                    skill_set = skill_set.intersection(curr_skill_set)

                #print("intersection=",skill_set)
            except KeyError as e:
                print("no skill set found",e)

    return skill_set


print(get_skills(skill_dict,'opportunity'))


In [ ]:
import urllib.request
from bs4 import BeautifulSoup


def get_page(topic):
    domain = "https://en.wikipedia.org"
    html = urllib.request.urlopen("https://en.wikipedia.org/w/index.php?search="+topic.replace(' ','+')+"&title=Special%3ASearch&go=Go")
    soup = BeautifulSoup(html, features="lxml")
    first_result = soup.find(attrs={"data-serp-pos": "0"})
    if first_result is None:
        print('page-found')
        return soup
    href = first_result.get('href')
    print('opening first-result')
    html = urllib.request.urlopen(domain+href)
    soup = BeautifulSoup(html, features="lxml")
    return soup


def get_first_para(topic):
    soup = get_page(topic)
    text_section = soup.find(attrs={'class': 'mw-parser-output'})
    text = ''
    for child in text_section.children:
        # print('for tag', child.name, child)
        try:
            if child is not None:
                if child.name == 'p':
                    text += child.text.lower()
                elif child.name == 'div' and 'toc' in child['class']:
                    break
        except Exception as e:
            print("exception", e)
    return text

vo_set = set()

In [ ]:
import re
# cleaning we _have 
dore = []
for x in we_have:
    regex = re.compile('[^a-zA-Z]')
    #First parameter is the replacement, second parameter is your input string
    #regex.sub('', x)
    dore.append(re.sub("[^a-zA-Z_ ]*", "", x))

for y in dore:
    print(y)

In [ ]:
import csv
with open('tech2.csv', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(dore)

In [ ]:
import nltk
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize


if __name__ == '__main__':

    #print(get_first_para('computer vision'))
    for original in dore: 
        print(original)
        w1=get_first_para(original)
        w2=word_tokenize(w1)
        
        print(w1)

        for word in w2:                                                                 
            if word not in stop and word.__len__()>3 and word.isalpha():
                w3 = get_skills(skill_dict, word)
                for x in w3:
                    vo_set.add(x)
                
                


In [ ]:
vo_set

In [ ]:
from nltk.stem import WordNetLemmatizer
import pickle


lemmatizer = WordNetLemmatizer()


def load_skill_set2():

    skill_dict = dict()
    pick_file = open("final_skill_dict_2.pickle", "rb")
    skill_dict = pickle.load(pick_file)
    pick_file.close()
    return skill_dict


def get_skill2(skill_dic,topic):
    return skill_dic[ lemmatizer.lemmatize(topic.strip()) ]


# skill_dict = make_skill_dict()
skill_dict2 = load_skill_set2()

print(get_skill2(skill_dict2,'procurement management'))



In [ ]:

print(len(vo_set))

In [ ]:
new_set = set()
for i in vo_set:
    if i in skill_dict2:
        new_set.add(get_skill2(skill_dict2,i))

len(new_set)

In [ ]:
print('--------------NON- TECHNICAL SKILLS---------------')
for word in new_set:
    print(word)
my_list2 = list(new_set)

In [ ]:
import csv
with open('nontech2.csv', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(my_list2)

In [ ]:
# trying out reading just the extract for the technical skills
import os
files = [os.path.join('testing_2', fi) for fi in os.listdir('testing_2')]
my_text = []
from nltk.tokenize import word_tokenize
for fil in files:
    with open(fil) as fi:
            line = fi.read()
            temp= word_tokenize(line)

In [ ]:
temp2 = list(temp)
my_text =  [w.lower() for w in temp2 if not w.lower() in stop]

In [ ]:
my_text

In [ ]:
q_set = set()
for q in my_text:
    if q in skill_dict:
        veu = get_skills(skill_dict,q)
        for qw in veu:
            q_set.add(qw)

In [ ]:
for qw in q_set:
    print(qw)

In [ ]:
len(q_set)

In [ ]:
qq_set = set()
for i in q_set:
    qq_set.add(get_skill2(skill_dict2,i))

In [ ]:
temp = []
for ele in qq_set:
    temp = temp + (word_tokenize(ele))

In [ ]:
dict123 = {}
my_final = {}
my_final['others'] = set()
print(temp)
for i in temp:
    if i in dict123:
        dict123[i] = dict123[i]+1
    else:
        dict123[i] = 1
for ele in qq_set:
    w = word_tokenize(ele)
    for i in w:
        if dict123[i]>5:
            if i in my_final:
                my_final[i].add(ele)
            else:
                my_final[i] = set()
                my_final[i].add(ele)
        if dict123[i]<2:
            my_final['others'].add(ele)
len(qq_set)
len(my_final)

In [ ]:
my_final

In [ ]:
### --------    Anupams dictionary  --------  ###


# from nltk.stem import WordNetLemmatizer
# import pickle
# import xlrd


# lemmatizer = WordNetLemmatizer()

# # print(sheet.cell_value(0,0))


# def make_skill_dict_final():

#     file = ("test_files/skills_anupam.xlsx")

#     wb = xlrd.open_workbook(file)
#     sheet = wb.sheet_by_index(0)

#     # print(len(lines))
#     skill_dict = {}

#     root_skill = ''
#     for i in range(sheet.nrows):
#         if sheet.cell_value(i,0) != '':
#             root_skill = lemmatizer.lemmatize(sheet.cell_value(i, 0).strip().lower())

#         for j in range(sheet.ncols):

#             if sheet.cell_value(i, j) != '':
#                 key = lemmatizer.lemmatize(sheet.cell_value(i, j).strip().lower())

#                 if key in skill_dict:
#                     skill_dict[key].add(root_skill)
#                 else:
#                     skill_dict[key] = {root_skill}

#     print("printing dict.......")
#     for key in skill_dict:
#         print(str(key).ljust(40) + str(skill_dict[key]).rjust(40))

#     pick_file = open("anupam_skill_dict.pickle","wb")
#     pickle.dump(skill_dict, pick_file)
#     pick_file.close()

#     return skill_dict


# def load_skill_set_final():

#     pick_file = open("anupam_skill_dict.pickle", "rb")
#     skill_dict = pickle.load(pick_file)
#     pick_file.close()
#     return skill_dict


# def get_skill_final(skill_dic,topic):
#     topic = lemmatizer.lemmatize(topic.strip().lower())
#     if topic in skill_dic:
#         return skill_dic[topic]
#     else:
#         return None


# # skill_dict = make_skill_dict()
# skill_dict_final = load_skill_set()

# print(get_skill_final(skill_dict_final,'motivate'))
# # while True:
# #     inp = input("topic:")
# #     print(get_skill(skill_dict,inp))

In [ ]:
print('----------------Technical skills---------------')
for zzz in dore:
    print(zzz)
print()
print('----------------Technical skills---------------')
print()

for i in my_final:
    
    print('--------------------------------')
    print('             --', i , '--')
    print('---------------------------------')
    for j in my_final[i]:
        print(j, ',')
        